In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [5]:
def r1 (x):  # if x is binary, then equivalent to NOT
    return 1-x 

def r2 (x):  # if x is binary, then equivalent to IDENTITY
    return x

# create tensor of size(T+1 X T+1 X 2) to store the cumulative loss (regret) of this step and the following steps 
# the first index is the number of times r1 is chosen, the second index is the number of times r2 is chosen 
# the third index is the cumulative future loss with respect to e1 and e2 
def get_regret_tensor(T):
    regret_tensor = np.zeros((T+1, T+1, 2))
    return regret_tensor

# the probability tensor is a tensor of size (T+1 X T+1 X 1) to store the probability of choosing r1 (choosing r2 is 1 - probability of choosing r1)
def get_probability_matrix(T):
    probability_matrix = np.zeros((T+1, T+1))
    return probability_matrix


T = 3
regret_tensor = get_regret_tensor(T)
P = get_probability_matrix(T)




def find_p(regret_tensor, i, j):
    


print (P)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
